<div class="announce ybox">
    <div class="contenidoAnnounce r5">
      <h5 class="mctaTittle bold">¡Gracias por actualizar tu cuenta!</h5>
      <p>Para mejorar nuestro servicio, contesta una encuesta y <br />
         participa en el sorteo para ganar un fabuloso premio.</p>
      <a href="<?php echo $this->url(array('controller' => 'encuesta','action' => 'index'),"",true); ?>" class="btnAll right qParticiparbtn"></a>      
      <a class="closer" href="#"></a>
    </div>
</div>