<? if (is_array($this->flashMessages)) : ?>
    <? foreach ($this->flashMessages as $msg) : ?>
        <div class="flash-message <?= $msg->level ?>">
            <div class="msgsTime msgYTIE">
                <div class="contenidoFlashMessage <?=
        ($msg->level == "success" ? 
            ((!empty($this->layout()->auth['suscriptor']['es_suscriptor']) && !empty($this->layout()->auth['suscriptor']['activo'])) ? "msgLoginOK" : "msgYellow") : (
            $msg->level == "info" ? "msgBlue" : (
                $msg->level == "error" ? "msgRed" : "")))
        ?> mB10 r5">
                    <?= $this->escape($msg->message) ?>
                </div>
            </div>
        </div>
    <? endforeach; ?>
<? endif; ?>