<div class="question">
    <h5><span class="vineta">2.</span> ¿Dónde realiza usualmente sus compras de vino?</h5>
    <div class="answer block">
        <div class="wrapper-control-group">
            <div class="control-group check-list">
                <div class="controls">
                <!--[if lte IE 7]>
                    <div class="list-radio-ie7">
                <![endif]-->
                    <label><input type="radio" tabindex="1" checked="checked" value="1" id="donde_compra_cv-1" name="donde_compra_cv">Supermercados</label>
                    <br>
                    <label><input type="radio" tabindex="1" value="2" id="donde_compra_cv-2" name="donde_compra_cv">Tiendas Especializadas</label>
                    <br>
                    <label><input type="radio" tabindex="1" value="3" id="donde_compra_cv-3" name="donde_compra_cv">Tiendas por internet</label>
                    <br>
                    <label class="left wauto last-radio"><input type="radio" tabindex="1" value="4" id="donde_compra_cv-4" name="donde_compra_cv">Otros</label>
                    <input type="text" tabindex="1" class="text inputNr otro-field" maxlength="50" value="" id="usualmente_otro_comentario_cv" name="usualmente_otro_comentario_cv" placeholder="-- Indique los lugares de compra --">
                    <div class="clear"></div>
                    <br>
                    <label class="last-radio"><input type="radio" tabindex="1" value="5" id="donde_compra_cv-5" name="donde_compra_cv">No compro regularmente</label>
                <!--[if lte IE 7]>
                     </div>
                <![endif]-->
                </div>
            </div>
        </div>
    </div>
</div>