<!--[if lte IE 7]>
        <div class="list-radio-ie7">
    <![endif]-->
    <label for="noparticipo_porque_2-1">
        <input type="radio" name="noparticipo_porque" id="noparticipo_porque_2-1" value="1" checked="checked" tabindex="1" />No le gusta participar en promociones
    </label>
    <br />
    <label for="noparticipo_porque_2-2">
        <input type="radio" name="noparticipo_porque" id="noparticipo_porque_2-2" value="2" tabindex="1" />Ninguna promoción le pareció atractiva
    </label>
    <br />
    <label for="noparticipo_porque_2-3" class="last-radio">
        <input type="radio" name="noparticipo_porque" id="noparticipo_porque_2-3" value="3" tabindex="1" />Otros
    </label>
    <input type="text" name="noparticipo_otros_comentario" id="noparticipo_otros_comentario" value="" maxLength="60" placeholder="-- Indique aqui su motivo --" class="text" maxlength="50" tabindex="1" />
    <!--[if lte IE 7]>
         </div>
    <![endif]-->
        
