 <? echo $this->partial('beneficio/_catalogo.phtml',
                                  array('mediaUrl' => $this->mediaUrl,
                                        'elementsUrl' => $this->elementsUrl,
                                        'busqueda_beneficios' => $this->busqueda_beneficios,
                                        'totalitems' => $this->totalitems,
                                        'MostrandoN' => $this->MostrandoN,
                                        'MostrandoDe' => $this->MostrandoDe,
                                        'cadenabusqueda' => $this->cadenabusqueda,
                                        'cadenabusquedaAll' => $this->cadenabusquedaAll,
                                        'ord' => $this->ord,
                                        'col' => $this->col,
                                        'itemsSeleccionados' => $this->itemsSeleccionados,
                                        'nombrecategoria' => $this->nombrecategoria,
                                        'messageSearch' => $this->messageSearch,
                                        'tipo'=>'imagenes',
                                        'sufixmedium'=> $this->sufixmedium,
                                        'sufixlittle'=> $this->sufixlittle,
                                        'idCategorias' => $this->idCategorias
                                  )
                       );
 ?>