<html> 
    <body>
        <table cellpadding=0 cellspacing=0 width="580px" align=center style="border:#cccccc 1px solid; background-color: #FFFFFF">
            <tr>
                <td>
                    <table cellpadding=0 cellspacing=0 width="94%" align=center>
                        <tr>
                            <td >
<!--                                <img src="< ?= MEDIA_URL ?>/images/emailing/logoBand.jpg" alt="logo Club de Suscriptores" border=0 height=50px>-->
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:justify;font-family:verdana;font-size:12px">
                                <?= $this->emailTemplate ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>