<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<table width="560" style="font:14px/17px Helvetica;">
		<tr>
			<td align="center">
				<table  width="535">
					<tr>
						<td>
							<table style="border-bottom:1px solid #DDDDDD;" width="100%">
								<tr>
									<td><a href="http://clubsuscriptores.pe"><img src="<?php echo $this->urlImagenes.'/logo.png'; ?>" alt="ClubSuscriptores.pe"/></a></td>
									<td style="text-align:right;">Confirmación de encuesta</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td>
							<div style="display:block;height:20px;width:20px;"></div>
						</td>
					</tr>
					<tr>
						<td>
							<table style="text-align:center;color:#666666;">
								<tr>
									<td style="text-align:left;">
										Hola <span style="text-decoration:underline;color:#0066CC;"><?php echo $this->nombre; ?></span>
									</td>
								</tr>
								<tr>
									<td>
										<div style="display:block;height:20px;width:20px;"></div>
									</td>
								</tr>
								<tr>
									<td style="font-size:24px;color:#000;">
										¡Gracias por participar en la encuesta!
									</td>
								</tr>
								<tr>
									<td>
										<div style="display:block;height:10px;width:20px;"></div>
									</td>
								</tr>
								<tr>
									<td style="text-align:left;">Este atento a nuestras novedades.</td>
								</tr>
								
							</table>
						</td>
					</tr>
					<tr>
						<td>
							<table style="border-top:1px solid #DDDDDD;" width="100%">
								<tr>
									<td style="color:#666666;font-size:12px;">
										<div style="display:block;height:25px;width:20px;"></div>
										Cordialmente,
										<div style="display:block;height:10px;width:20px;"></div>
									</td>
								</tr>
								<tr>
									<td>
										<b style="font-size:16px;color:#000000;">El Equipo de Club de Suscriptores</b>
										<div style="display:block;height:10px;width:20px;"></div>
									</td>
								</tr>
								<tr>
									<td style="font-size:11px;color:#666666;">Para cualquier consulta no dudes en enviarnos un e-mail o llamarnos al teléfono: 311-5100</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</body>
</html>