<span style="font-weight: bold;">Nombres :</span>
<span><?php echo $this->nombres; ?></span><br/>
<span style="font-weight: bold;">Apellidos :</span>
<span><?php echo $this->apellidos; ?></span><br/>
<span style="font-weight: bold;">Documento :</span>
<span><?php echo $this->tipo_documento.' - '.$this->nro_documento; ?></span><br/>
<span style="font-weight: bold;">Teléfonos :</span>
<span><?php echo $this->telefonos; ?></span><br/>
<span style="font-weight: bold;">Email :</span>
<span><a href="mailto:<?php echo $this->email; ?>"><?php echo $this->email; ?></a></span><br/>
<span style="font-weight: bold;">Mensaje :</span>
<span><?php echo $this->mensaje; ?></span><br/>
<br/><br/>
<span style="color: #666666;">Este es un correo generado de forma automática por el Club de Suscriptores</span>
<br><br>