<tr><td height=80px><img src="Images/logo-ClubSuscriptores.gif" alt=0 border=0 height=50px></td></tr>
<tr><td style="text-align:justify;font-family:verdana;font-size:12px">
<br><P align=center><font size=3>
<b><?= $this->nombre ?>, <?= $this->empresa ?> te ha enviado un mensaje dentro de su  proceso de Selección para el puesto de <?= $this->puesto ?></b></font></P>
<br>
Tus datos de acceso son: <BR>
<span style="color:#000000;font-size:13px"><b>Usuario    : </b></span><span style="color:#3366ff;font-size:13px;"><b><?= $this->email ?></b></span><BR>
<br><br>
Eres parte del proceso de Selección de la empresa <?= $this->empresa ?> para el puesto de <?=$this->puesta ?> y la empresa te ha enviado un mensaje:
<br><br>
<P align=center style="color:#3366ff"><a href="http://ClubSuscriptores.pe"><b>Ver Mensaje</b></a></P>
<br>éxitos!
<br/><br/>
<b>Administrador del Club</b>
<br><br>