<span style="font-weight: bold;">Codigo Suscriptor :</span>
<span><?php echo $this->codigo; ?></span><br/>
<span style="font-weight: bold;">Nombres y Apellidos :</span>
<span><?php echo $this->nombres; ?></span><br/>
<h2><?php echo $this->categoria; ?></h2><br/>
<span style="font-weight: bold;">Titulo :</span>
<span><?php echo $this->titulo_consulta; ?></span><br/>
<span style="font-weight: bold;">Mensaje :</span>
<span><?php echo $this->mensaje; ?></span><br/>
<br/><br/>
<span style="color: #666666;">Este es un correo generado de forma automática por el Club de Suscriptores</span>
<br><br>