<strong>Bienvenido a ClubSuscriptores.pe</strong>
<br/>

Has sido registrado en nuestro sistema como "<?=$this->perfil?>". <br/><br/>
Para acceder al sistema tus credenciales son:<br/>
Nombre de usuario: <?=$this->to?> <br />
Password: <?=$this->pswd?>
<br/><br/>
Puedes ingresar al sistema mediante el siguiente url <a href="<?=$this->url?>" ><?=$this->url?></a>.
<br/><br/>
Gracias por tu atención.
<br/><br/>
<b>Administrador del Club</b>
<br/><br/>