<br/>
Hola <?= $this->nombre ?>,
<br/><br/>
!Tu suscripcion ha sido completado con éxito!
<br/><br/><br/>
Ahora puedes disfrutar todas las promociones y productos de <br>
Club Suscriptores. No dejes de ingresar para ver las novedades <br>
que tenemos: <span style="color:#3366ff"><b>www.clubsuscriptores.pe</b></span>
<br/><br/>
<br/><br/>
<br/><br/>
¡Nos vemos en el portal!
<br/><br/>
<b>Administrador del Club</b>
<br><br>