<br/>
<p align=center>
  <font size=3>
  <b>¡¡ <?= $this->nombre ?>, ya eres parte del Club Suscriptor de El Comercio !!</b></font></P>
<br/><br/>
Ahora ingresando con tu e-mail y contraseña a: <span style="color:#3366ff"><b>www.clubsuscriptores.pe</b></span>
 encontrarás las mejores promociones y ofertas en cientos de establecimientos afiliados a nuestro Club. No dejes de ingresar para ver las novedades que tenemos para tí y participar de nuestros sorteos frecuentes.
 <br/><br/>
Tus datos de acceso son: 
<br/>
<span style="color:#000000;font-size:13px"><b>Usuario    : </b></span><span style="color:#3366ff;font-size:13px"><b><?= $this->user ?></b></span><br/>
<span style="color:#000000;font-size:13px"><b>Contraseña : </b></span><span style="color:#3366ff;font-size:13px"><b><?= $this->pswd ?></b></span>
<br/><br/>
<br/><br/>
¡Nos vemos en el portal!
<br/><br/>
<b>Administrador del Club</b>
<br><br>