<br/>
<p align=center>
  <font size=3>
  <b>¡¡ Club Suscriptor de El Comercio !!</b></font></P>
<br/><br/>
Ahora ingresando con tu e-mail y contraseña a: <a href="<?=$this->url?>"> <span style="color:#3366ff" ><b><?=$this->url?></b></span></a>
<br/><br/>
Su contraseña ha sido cambiada.
<br/>
Tu nueva contraseña es : <span style="color:#3366ff;font-size:13px"><b><?= $this->pswd ?></b></span>
<br/>
<br/><br/>
¡Nos vemos en el portal!
<br/><br/>
<b>Administrador del Club</b>
<br><br>