<?php $recuperarClave = $this->url(array('module' => 'suscriptor', 'controller' => 'auth', 'action' => 'generar-clave', 'key' => $this->urlToken), 'default', true) ?>
<br><P align=center><font size=3>
<b>Cambio de Contraseña en el Club de Suscriptores</b></font></P>
<br/>
Para cambiar la contraseña de su cuenta 
    <span style="color:#3366ff"><b><?php echo $this->email; ?></b></span> en el Club de Suscriptores, 
    asociada al establecimiento <b><?= $this->establecimiento ?></b>, debe hacer click en el siguiente enlace: 
    <span style="color:#3366ff"><b><a href="<?= SITE_URL ?><?= $recuperarClave ?>" alt="URL Token"><?= SITE_URL ?><?= $recuperarClave ?></a></b></span>.
<br/><br/><br/>
¡Gracias por ser parte de nuestro Club!
<br/>
<br/><br/>
<b>Administrador del Club</b>
<br><br>