<?php if (!empty($this->encuesta)):?>
<div id="tesTBox" class="grayborder2 mB20 r5">
  <h3 class="mbgray bold font18">ENCUESTAS</h3>
  <form id="formencuesta" name="formencuesta" action="" method="post">
    <input type="hidden" name="encuesta_id" id="encuesta_id" value="<?php echo $this->encuesta['id']; ?>"/>
    <p class="textoEncuesta fnormal"><?php echo $this->escape($this->encuesta['pregunta']); ?></p>
    <fieldset class="fielserEncuesta">
    <?php foreach ($this->opciones as $op):?>
    <label class="block"> 
    	<input type="radio" class="inputEncT noBdr left" name="rbtnop" value="<?php echo $this->escape($op['id']);?>"/>
    	<span class="spanEncT right"><?php echo $this->escape($op['opcion']); ?></span>
    </label>
    <?php endforeach; ?>
    <!-- <label class="block"> <input type="radio" /><span class="ml5 fnormal">No</span> </label>
    <label class="block"> <input type="radio" /><span class="ml5 fnormal">No sabe/No opina</span> </label> -->
    </fieldset>
    <fieldset class="all">
    <div class="all alignC"><a href="#winVerEncuesta" class="encuestaVer fnormal winModal noScrollTop">Ver resultados</a></div>
   <?php //if(!$this->existe_voto): ?><div class="all"><input type="button" id="btnVotar" value="" class="btnAll btnVotar" /></div>
   <?php //else:?> <!--<div style="width: 75px;height: 32px;margin: 10px 0 6px 192px;"></div>-->
   <?php //endif; ?>
   </fieldset>
  </form>
</div>
<?php endif;?>