<div id="content-follow">
  <div id="socialRedsBox" class="grayborder2 mB20 r5 ">
    <h3 class="mbgray bold font18"> SÍGUENOS </h3>
  </div>
  <a class="twitter sptAll iTooltip" href="<?php echo $this->cuentas['twitter']; ?>" rel="nofollow" target="_blank"><span class="tip">Síguenos en Twitter</span></a>
  <a class="facebook sptAll iTooltip" href="<?php echo $this->cuentas['facebook']; ?>" rel="nofollow" target="_blank"><span class="tip">Síguenos en Facebook</span></a>
  <a class="youtube sptAll iTooltip" href="<?php echo $this->cuentas['youtube']; ?>" rel="nofollow" target="_blank"><span class="tip">Síguenos en Youtube</span></a>
  <a class="google_s sptAll iTooltip" href="<?php echo $this->cuentas['googleplus']; ?>" rel="nofollow" target="_blank"><span class="tip">Síguenos en Google+</span></a>
</div>