<div id="main-content" class="gridS20">
	<div id="main-content2" class="grid20">
		<div id="content" class="grid14 left">
			<div id="TopboxBack">
				<div id="topBox" class="grayborder2 mB20 r5">
					<h1 class="Titulo680 titleFix bold font18">PREGUNTAS FRECUENTES</h1>
					<div class="m10all">
						<div class="imgPreguntasf" >
							<div class="nuemroPreguntasf left">
								P1
							</div>
							<div class="txtPreguntasf left">
								¿Cómo puedo pertenecer al Club de Suscriptores?
							</div>
						</div>
						<div class=" m10all bbSolid">
							<p class="f14">
								Sólo tienes que suscribirte  al Diario El Comercio llamando al <strong>3115100</strong>. Tienes 9 paquetes para escoger los días que deseas que te llegue el diario de acuerdo a tus preferencias.
							</p>
						</div>                        
<!--						<div class="m10all bbSolid">
                            
							<p>
								Suscribiéndote a cualquier diario o revista del Grupo El Comercio
								<ul>
									<li class="f14 black">
										1.       Diario el Comercio
									</li>
									<li class="f14 black">
										2.       Diario Gestión
									</li>
									<li class="f14 black">
										3.       Gestión On Line
									</li>
									<li class="f14 black">
										4.       Revista Hola
									</li>
									<li class="f14 black">
										5.       Revista Vamos
									</li>
									<li class="f14 black">
										6.       Revista Ruedas & Tuercas
									</li>
									<li class="f14 black">
										7.       Revista G de Gestión
									</li>
									<li class="f14 black">
										8.       Revista Casa y Más
									</li>
								</ul>
							</p>
							<div class="imgpreguntasP1"></div>
						</div>-->
					</div>
					<div class="m10all">
						<div class="imgPreguntasfV2">
							<div class="nuemroPreguntasf left">
								P2
							</div>
							<div class="txtPreguntasf left">
								¿El beneficiario adicional tiene los mismos beneficios que el suscriptor?
							</div>
						</div>
						<div class=" m10all bbSolid">
							<p class="f14">
								Sí, el beneficiario  adicional podrá acceder a todas las promociones de igual forma que el suscriptor.
							</p>
						</div>                          
<!--						<div class=" m10all bbSolid">
							<p class="f14">
								No, existen dos tipos de suscriptores, Gold y Platinium. Los beneficios son
								<br />
								diferenciados para cada uno.
							</p>
						</div>-->
<!--						<div class="imgpreguntasP2"></div>-->
					</div>
<!--					<div class="m10all">
						<div class="imgPreguntasf" >
							<div class="nuemroPreguntasf left">
								P3
							</div>
							<div class="txtPreguntasf left">
								¿Cómo actualizo mis datos?
							</div>
						</div>
						<div class=" m10all bbSolid">
							<p class="f14">
								Entra a <a href="http://www.actualizatusdatos.pe">aquí</a>  y llena el formulario de Actualización de Datos. Ahí podrás además inscribir a tu beneficiario adicional.
							</p>
						</div>
					</div>-->
					<div class="m10all">
						<div class="imgPreguntasf">
							<div class="nuemroPreguntasf left">
								P3
							</div>
							<div class="txtPreguntasf left">
								¿Cómo hago uso de las promociones?
							</div>
						</div>
						<div class=" m10all">
							<p class="f14">
								Para hacer uso de los descuentos sigue los siguientes pasos:
                                <p>
                                    <ul>
                                        <li class="f14 black">
                                            1. Indica que eres Suscriptor de El Comercio.
                                        </li>
                                        <li class="f14 black">
                                            2. Identifícate con tu DNI.
                                        </li>
                                        <li class="f14 black">
                                            3. Disfruta de tu descuento.
                                        </li>
                                    </ul>
                                </p>
                                Para participar en los sorteos deberás registrarte con tu usuario y contraseña e  imprimir tu cupón de acreditación.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--SIDEBAR -->
		<div id="sidebar" class="grid6">
			<div id="socialifeBox" class="grayborder2 mB20 r5">
				<h6 class="mbgray bold">ATENCIÓN AL SUSCRIPTOR</h6>
				<p class="vidaSocialBajada Trebuchet">
					Ponemos a tu disposición nuestra Central de Atención al Cliente para cualquier duda o consulta sobre nuestros beneficios.
				</p>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">Horario de atención:</span>
					<p class=" Trebuchet11 c3">
						Lunes a Viernes: 7am - 5pm
						<br />
						Sábados - Domingos y feriados: 7am - 1pm
					</p>
				</div>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">Central telefónica</span>
					<p class=" Trebuchet11 c3">
						311-5100
					</p>
				</div>
				<p class="vidaSocialBajada Trebuchet">
					También puedes escribirnos a nuestra dirección de correo electrónico.
				</p>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">E-mail:</span>
					<p class=" Trebuchet11 c3">
						<a class="Trebuchet" >clubdesuscriptores@comercio.com.pe</a>
					</p>
				</div>
			</div>
		</div>
	</div>
		<!--SIDEBAR -->
		<div id="sidebar" class="grid6">
			<div id="socialifeBox" class="grayborder2 mB20 r5">
				<h6 class="mbgray" "bold">ATENCIÓN AL SUSCRIPTOR</h6>
				<p class="vidaSocialBajada Trebuchet">
					Para alguna duda o pregunta puedes contactarnos a la Central telefónica o escribirnos al mail.
				</p>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">Horario de atención:</span>
					<p class=" Trebuchet11 c3">
						Lunes a Viernes: 8am-6pm
						<br />
						Sábado: 8am-1pm
					</p>
				</div>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">Central telefónica</span>
					<p class=" Trebuchet11 c3">
						311-5100
					</p>
				</div>
				<p class="vidaSocialBajada Trebuchet">
					Escribe a este e-mail si es referente a la entraga de la suscripción o solicitud de nuevas suscripciones.
				</p>
				<div id="horarioAtencion" class=" Trebuchet">
					<span class="cshrTitle mbgray Trebuchet14 bold">E-mail:</span>
					<p class=" Trebuchet11 c3">
						<a class="Trebuchet" >club@elcomercio.pe</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>