<div id="main-content2" class="grid20">
    <div id="content" class="left grid14">
<!--        <div id="TopboxBack">
            <div id="topBox" class="grayborder2 mB20 r5">

                <div class="flowWAll">	 
                    <h6 class="Titulo680 bold">SERVICIOS AL SUSCRIPTOR</h6>
                    <h2 id="titunuevasVentajas"></h2>
                    <div id="ventajas-img">                    
                        <div id="iVentajas-img">
                            <div id="inVentajas-img">
                                <div class="caja_nuevaventajSS">
                                    <div class="imgServPhoto left">
                                        <img src="<?php echo $this->mediaUrl; ?>/images/caribe.jpg" width="180" height="102" alt="Club del suscriptor"/>
                                    </div>
                                    <div id="descripNVentajas" class="right">
                                        <h6 class="TitulodeEstaP">Descuentos para ti y tu familia para el Caribe</h6>
                                        <p class="ftxt14 fnormal c3">
                                            Conóce nuevas amistades y playas
                                        </p>
                                    </div>
                                </div>
                                <div class="caja_nuevaventajSS">
                                    <div class="imgServPhoto left">
                                        <img src="<?php echo $this->mediaUrl; ?>/images/cine.jpg" width="180" height="102" alt="Club del suscriptor"/>
                                    </div>
                                    <div id="descripNVentajas" class="right">
                                        <h6 class="TitulodeEstaP">Asiste a toda la temporada del festival de cine de Lima</h6>
                                        <p class="ftxt14 fnormal c3">
                                            Asiste a las proyecciones y premiaciones
                                        </p>
                                    </div>
                                </div>
                            </div>    
                        </div>

                        <div id="cajatxtSS" >
                            <div class="f16">Suscríbete a El Comercio y disfruta de los beneficios de pertenecer a nuestra comunidad de suscriptores.</div>
                            <div id="worldOfNV"><img src="<?php echo $this->mediaUrl; ?>/images/CsVentajas.jpg" alt="Club del suscriptor"/></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>-->
        <div id="bottomBox" class="grayborder2 r5">
            <div class="flowWAll">	
                <h6 class="Titulo680 bold">PAQUETES Y PRECIOS</h6>
                <div id="destacadosContainer">
                    <div id="blockSrvc" class="noLineD">
                        <div id="promo1Content"></div>
                        <div id="firstdescription">
                            <div class="mictaContet grayborder2 r3" id="tableServSus">
                                <table id="mictBenContentA">
                                    <thead id="mictaBenTitle">
                                        <tr>
                                            <th width="34%" class="mictBenTiTH ml5 mictbRight bold">Paquete</th>
                                            <th width="40%" class="mictBenTiTH ml5 mictbRight bold">Días</th>
                                            <th width="26%" class="mictBenTiTH ml5 bold">Costo Mensual (Incl. IGV)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr >
                                            <td class="mictBenFluTd mictbTop bold">Familiar</td>
                                            <td class="mictBenFluTd mictbTop">Lunes - Domingo</td>
                                            <td class="mictBenFluTd mictbTop">S/. 65</td>
                                        </tr>
                                        <tr>
                                            <td class="mictBenFluTd mictbTop bold">Corporativo</td>
                                            <td class="mictBenFluTd mictbTop">Lunes - Viernes</td>
                                            <td class="mictBenFluTd mictbTop">S/. 44</td>
                                        </tr>
                                        <tr >
                                            <td class="mictBenFluTd mictbTop bold">Femenino</td>
                                            <td class="mictBenFluTd mictbTop">Sábado, Domingo, Martes y Jueves</td>
                                            <td class="mictBenFluTd mictbTop">S/. 41</td>
                                        </tr>
                                        <tr>
                                            <td class="mictBenFluTd mictbTop bold">Cultural y Entretenimiento</td>
                                            <td class="mictBenFluTd mictbTop">Sábado, Domingo, Miércoles y Viernes</td>
                                            <td class="mictBenFluTd mictbTop">S/. 41</td>
                                        </tr>
                                        <tr >
                                            <td class="mictBenFluTd mictbTop bold">Distracción y Entretenimiento</td>
                                            <td class="mictBenFluTd mictbTop">Martes, Jueves, Viernes y Sábado</td>
                                            <td class="mictBenFluTd mictbTop">S/. 37</td>
                                        </tr>
                                        <tr>
                                            <td class="mictBenFluTd mictbTop bold">Ejecutivo</td>
                                            <td class="mictBenFluTd mictbTop">Sábado, Domingo y Lunes</td>
                                            <td class="mictBenFluTd mictbTop">S/. 35</td>
                                        </tr>
                                        <tr >
                                            <td class="mictBenFluTd mictbTop bold">Entretenimiento</td>
                                            <td class="mictBenFluTd mictbTop">Sábado, Domingo y Viernes</td>
                                            <td class="mictBenFluTd mictbTop">S/. 35</td>
                                        </tr>
                                        <tr>
                                            <td class="mictBenFluTd mictbTop bold">Geniogramista</td>
                                            <td class="mictBenFluTd mictbTop">Martes, Jueves y Sábado</td>
                                            <td class="mictBenFluTd mictbTop">S/. 28</td>
                                        </tr>
                                        <tr >
                                            <td class="mictBenFluTd mictbTop bold">Fin de Semana</td>
                                            <td class="mictBenFluTd mictbTop">Sábado y Domingo</td>
                                            <td class="mictBenFluTd mictbTop">S/. 26</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div>
                            <a href="<?php echo $this->url(array(), 'suscribete', true); ?>" id="MainSuscribe" class="btnAll"> </a>
                        </div>
                    </div>
                </div>
            </div>	
        </div>
    </div>
    <!--SIDEBAR -->
    <div id="sidebar" class="grid6 right">
        
        <?php //echo $this->partial('home/_siguenos.phtml',array('cuentas'=> $this->cuentas)); ?>
        
        <div id="content-viewproducts">
            <div id="viewproducts" class="grayborder2 mB20 r5">
                <h6 class="mbgray bold">CATÁLOGO</h6>
                <div id="catalogoImg"></div>
                <a id="print-products" class="btnAll" target="_blank" href="<?php echo $this->siteUrl; ?>/magazine/mostrar-catalogo/"></a>
            </div>
        </div>
        <?php echo $this->partial('home/_articulo.phtml', array('portada_articulo' => $this->portada_articulo, 'imagenes_articulo' => $this->imagenes_articulo, 'elementsUrl' => $this->elementsUrl,'mediaUrl'=>$this->mediaUrl, 'sufixlittle' => $this->sufixlittle)); ?>

        <?php echo $this->partial('home/_encuesta.phtml', array('encuesta' => $this->encuesta, 'opciones' => $this->opciones, 'existe_voto' => $this->existe_voto)); ?>
    </div>
</div>