<?php
$fechaini = new Zend_Date($this->encuesta['fecha_inicio']);
$fechafin = new Zend_Date($this->encuesta['fecha_fin']);
$fechareg = new Zend_Date($this->encuesta['fecha_registro']);
//$now = new Zend_Date();
//echo $now->toString('YYYY-MM-dd HH:mm:ss').' - '.$now; exit;
?>

  <h6 class="TilutoLightbox">Encuesta: <?php echo $this->escape($this->encuesta['nombre']); ?></h6>
  <div id="EncuestaTittle"><?php echo $this->escape($this->encuesta['pregunta']); ?></div>
  <div id="dateLiTo">
   <span class="black">INICIO: <?php echo $fechareg->toString(Zend_Date::DATES); ?></span>
   <span class="black ml5">
       <?php //echo 'FIN: '.$fechafin->toString(Zend_Date::DATES); ?>
   </span>
   </div>
  <div id="GraphicsTest" class="mT20 bbSolid bTsolid contentGraphEView">
      <?php foreach ($this->resultado_encuesta as $opciones):
            $cant = (!empty($this->total_votos['tvotos'])?$this->total_votos['tvotos']:1);
      		$porcent = round((($opciones['votos']*100)/$cant),0);
      ?>
      <div class="TestBlock mT20">
          <div class="SecondBlockTest grid7 blSolidSblockTest barra" style="width: <?php echo $porcent.'%'; ?>">
              <input type="hidden" value="<?php echo $porcent; ?>" name="opt<?php echo $opciones['id']; ?>" id="opt<?php echo $opciones['id']; ?>"/>
          </div>
          <div class=" ml10 mT5 Trebuchet">
              <span class="black bold"><?php echo $porcent.'%'; ?></span>
              <span class="gray">&nbsp;&nbsp;<?php echo $this->escape($opciones['opcion']).' ('.(empty($opciones['votos'])?0:$opciones['votos']).' voto'.($opciones['votos']==1?'':'s').')'; ?></span>
          </div>
      </div>
      <?php endforeach;?>
  </div>
  <div id="TestVer" class="bold">Votos: <?php echo (!empty($this->total_votos['tvotos'])?$this->total_votos['tvotos']:0); ?></div>
<script type="text/javascript">
    <?php foreach($this->opciones_mas as $max):?>
        $('#opt<?php echo $max['id']; ?>').parent()
            .removeClass('SecondBlockTest blSolidSblockTest')
            .addClass('firstBlockTest blSolidfirstBlockTest');
    <?php endforeach;?>
    
    <?php foreach($this->opciones_menos as $min):?>
        $('#opt<?php echo $min['id']; ?>').parent()
            .removeClass('SecondBlockTest blSolidSblockTest')
            .addClass('fourthBlockTest blSolidFblockTest');
    <?php endforeach;?>
    /*var objmx = null, objmn = null, max = 0, min = 999;
    $('.barra input').each(function(){
        var eval = Math.round($(this).val());
        if(eval>max){
            max = $(this).val();
            objmx = $(this);
        }
        if(eval<min){
            min = $(this).val();
            objmn = $(this);
        }
    });
    if(objmx && objmn){
        objmx.parent().removeClass('SecondBlockTest blSolidSblockTest')
                      .addClass('firstBlockTest blSolidfirstBlockTest');
        objmn.parent().removeClass('SecondBlockTest blSolidSblockTest')
                      .addClass('fourthBlockTest blSolidFblockTest');
    }*/
    //firstBlockTest blSolidfirstBlockTest //color yellow
    //fourthBlockTest blSolidFblockTest //color red
    //SecondBlockTest blSolidSblockTest //color orange
</script>