<div id="boxes">
    <!-- mensaje -->
    <div id="modalInfo" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <h6 class="TilutoLightbox">Mensaje de confirmación</h6>
                    <div id="diagContent" class="infoDialog"></div> 
                    <div class="btnMsjModal hide">
                        <a id="vencOk" class="adminAceptBtn left"></a>
                        <a class="adminQuitBtnbene closeWM left" href="#"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>    
    <!-- Edicion beneficio -->
    <div id="editBene" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="iEditBene"></div>
                </div>
            </div>
        </div>     
    </div>    
    <!-- Vista previa -->
    <div id="previewBene" class="window initModal">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="iVistaPrevia" class="all"></div>
                </div>
            </div>
        </div>     
    </div>    

    <div id="lboxEresultado" class="window">
        <div class="innerWin"> <a href="#Cerrar" id="idCerrarEG" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div id="content-winViewEncuestaG" class="bLB3 r5 inWindow">
                    <!-- Aqui va el HTML para el Modal --> 
                    
                    <!-- /Fin de HTML Modal -->
                </div>
            </div>
        </div>
    </div>
    <!-- Ventana de Ver Vida Social : Ver Vida Social -->
    <div id="winModUsuario" class="window">
        <div class="innerWin"> 
            <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winModUsuario" class="all">
                        <!--verProceso-->
                    </div>
                </div>    
            </div>
        </div>
    </div>

    <div class="window" id="loginModalW">
        <div class="innerWin"> <a class="sptAll closeWM icoCWM" href="#Cerrar"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winCategoria" class="all">
                        <!--verProceso-->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="window" id="adminGesCategModal">
        <div class="innerWin"> <a class="sptAll closeWM icoCWM" href="#Cerrar"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winCambioEstado" class="all">
                        <!--verProceso-->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="beneVencer" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                 <div class="bLB3 r5 inWindow">
                    <h6 class="TilutoLightbox">Vencer Beneficio</h6>
                    <div class="block pl10 bold" id="vcont"> 
                        <span class="Trebuchet14 gray">¿Estás seguro que deseas pasar a no vigente este beneficio?</span>
                    </div> 
                    <div id="adminSaveCancEB" class="marginCero">
                        <a id="aceptVenBtn" class="adminAceptBtn left" href="#"></a>
                        <a class="adminQuitBtnbene left closeWM" href="#"></a>
                    </div>
                    <!-- /Fin de HTML Modal --> 
                </div>
            </div>
        </div>
    </div>



    
 

<div id="edit-picture" class="window" style="left: 30%; top: 40%;">
  <div class="innerWin"><a id="idCloseChangeE" href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
    <div class="iWindow r5">
      <div class="bLB3 r5 inWindow">
        <h6 class="TilutoLightboxES">Editar Foto</h6>
        <span class="adminCclaveTi">Leyenda de foto:</span>

<?php /*<span class="adminCclaveTi"><img height="300" src="" border="0" class="editImageonLive"></span>*/ ?>

        <div id="bgmiAdminClave">
          <form id="" action="" method="post" onsubmit="return false;">
            <fieldset id="" class="field textoinput pl10">
              <div class="block mB0">
                <input type="text" id="edit-image-desc" name="edit-image-desc"maxlength="120">
                <input type="hidden" id="edit-id-image" name="edit-id-image" maxlength="10">
              </div>
              <div id="error_sinstructions" class="block mB0">
              <span id="me_sinstructions"></span>
              </div>
              <div class="bloque">
                <input type="submit" id="saveChangesBt2" value="" class="btnAll saveChangesBt" tabindex="4"/>
              </div>
              <div class="hide messageChangePassE" id="idMessageChangePassE"></div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>




    <div id="winAlertEstablecimiento" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                 <div class="bLB3 r5 inWindow contenedor all">
                     <div class="elimEstablecimiento">
	<h6 class="TilutoLightbox">Mensaje de confirmación</h6>
                        <div class="block grid12 pl10 bold" id="vcont"> 
                            <span class="Trebuchet14 gray">¿Está seguro que desea eliminar este Establecimiento?</span>
                        </div> 
                        <div class="btnMsjModal">
                            <a id="aceptVenBtn" class="adminAceptBtn btnEliminar left" href="#"></a>
                            <a class="adminQuitBtnbene left closeWM" href="#"></a>
                        </div>
                        <!-- /Fin de HTML Modal -->
                    </div> 
                </div>
            </div>
        </div>
    </div>
    
    
    <div id="winAlertCategoria" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                 <div class="bLB3 r5 inWindow contenedor all">
                     <div class="elimCategoria">
	<h6 class="TilutoLightbox">Mensaje de confirmación</h6>
                        <div class="block grid12 pl10 bold" id="vcont"> 
                            <span class="Trebuchet14 gray">¿Está seguro que desea eliminar esta Categoría?</span>
                        </div> 
                        <div class="btnMsjModal">
                            <a id="aceptVenBtn" class="adminAceptBtn btnEliminarCate left" href="#"></a>
                            <a class="adminQuitBtnbene left closeWM" href="#"></a>
                        </div>
                        <!-- /Fin de HTML Modal -->
                    </div> 
                </div>
            </div>
        </div>
    </div>
    
    <div id="wBoxGEnc" class="window modalInfo grid8">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow" id="content-winViewPrevEncG">
                    
                </div>
            </div>
        </div>
    </div>

    <div id="winVerVidaSocial" class="window">
        <div class="innerWin">
            <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winVerVidaSocial" class="all"></div>
                </div>
            </div>
        </div>
    </div>
    
    <div id="divEditParameter" class="window modalAdminGesPar">
        <div class="innerWin"> <a href="#Cerrar" id="idCloseEditParamG" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
          <div class="iWindow r5">
            <div id="content-divEditParameter" class="bLB3 r5 inWindow">
              
            </div>
          </div>
        </div>
      </div>

    <!-- Window modal Telefonos de Establecimiento -->
    <div id="divAddNumbersPhone" class="window">
        <div class="innerWin"> <a href="#Cerrar" id="idClosePhoneG" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div id="content-divAddNumbersPhone" class="bLB3 r5 inWindow">
                
                </div>
            </div>
        </div>
    </div>

    <div id="editConciliacion" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="iEditConciliacion"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="encuestBaja" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                 <div class="bLB3 r5 inWindow">
                    <h6 class="TilutoLightbox">Baja de Encuesta</h6>
                    <div class="block pl10 bold" id="vcont"> 
                        <span class="Trebuchet14 gray">¿Estás seguro que deseas dar de baja a la encuesta?</span>
                    </div> 
                    <div id="adminSaveCancEB" class="marginCero">
                        <a id="aceptBajaEncBtn" class="adminAceptBtn left" href="#"></a>
                        <a id="aCloseBajaE" class="adminQuitBtnbene left closeWM" href="#"></a>
                    </div>
                    <span id="divMessageBajaE"></span>
                    <!-- /Fin de HTML Modal --> 
                </div>
            </div>
        </div>
    </div>
    
    <div id="vidaSocialBaja" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                 <div class="bLB3 r5 inWindow">
                    <h6 class="TilutoLightbox">Baja de Evento</h6>
                    <div class="block pl10 bold" id="vcont"> 
                        <span class="Trebuchet14 gray">¿Estás seguro que deseas dar de baja a este evento?</span>
                    </div>
                    <div id="adminSaveCancEB" class="marginCero">
                        <a id="aceptBajaArtBtn" class="adminAceptBtn left" href="#"></a>
                        <a id="aCloseBajaA" class="adminQuitBtnbene left closeWM" href="#"></a>
                    </div>
                    <span id="divMessageBajaA"></span>
                    <!-- /Fin de HTML Modal --> 
                </div>
            </div>
        </div>
    </div>
    
    <div id="darBajaBeneficio" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" id="aCloseBajaBenef" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow" id="content-darBajaBeneficio">
                    
                </div>
            </div>
        </div>
    </div>
    
    <div id="eliminarAnunciante" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" id="aCloseAnunciante" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow" id="content-eliminarAnunciante">
                    
                </div>
            </div>
        </div>
    </div>
    
    
    <!-- Ventana Cambiar Contraseña : Establecimiento -->
    <?php if(!empty($this->layout()->frmChangePassE)):
        $frmChangePassword = $this->layout()->frmChangePassE; ?>
    <div id="winChangePassE" class="window">
        <div class="innerWin"> <a id="idCloseChangeE" href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
          <div class="iWindow r5">
              <div class="bLB3 r5 inWindow">
                
                <h6 class="TilutoLightboxES">Cambio de Clave</h6>
                <span class="adminCclaveTi">Para cambiar tu clave, ingresa los siguientes datos:</span>
                  
                <div id="bgmiAdminClave">
                    <form id="cClaveCP" action="<?=SITE_URL.$frmChangePassword->getAction(); ?>" method="post">
                      <fieldset id="mictaCambioClave" class="field textoinput pl10">
                        <div class="block mB0">
                          <label class="adminEslabelN" for="fACtns"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña antigua: </label>
                            <?= $frmChangePassword->oldpswd->setAttribs(array('id' => 'fACtns', 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->oldpswd->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->oldpswd->errMsg : '' ?></span>
                        </div>
                        <div class="block left mB0">
                          <label class="adminEslabelN" for="fClave"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña nueva: </label>
                            <?= $frmChangePassword->pswd->setAttribs(array('id' => 'fClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->pswd->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd->errMsg : '' ?></span>
                        </div>
                        <div class="block mB0">
                          <label class="adminEslabelN" for="fRClave"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña nueva:<br/>(confirmación) </label>
                            <?= $frmChangePassword->pswd2->setAttribs(array('id' => 'fRClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->pswd2->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd2->errMsg : '' ?> </span>
                        </div>
                        <div class="bloque">
                            <input type="submit" id="saveChangesBt" value="" class="btnAll saveChangesBt" tabindex="4"/>
                        </div>
                        <div class="hide messageChangePassE" id="idMessageChangePassE"></div>
                      </fieldset>
                    </form>
                </div>
                
            </div>
          </div>
        </div>
    </div>
    <?php endif; ?>
    
    <div id="mask"></div>
</div>
