<div id="boxes">

    <div id="winModClaveAdm" class="window modalInfo">
        <div class="innerWin"> 
            <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winModClaveAdm" class="all">
                        <!--verProceso-->
                    </div>
                </div>    
            </div>
        </div>
    </div>


    <div id="winEditarUsuarioAdm" class="window modalInfo">
        <div class="innerWin"> 
            <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winEditarUsuarioAdm" class="all">
                        <!--verProceso-->
                    </div>
                </div>    
            </div>
        </div>
    </div>

    <div id="lboxEusuarioEdicion" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">  
                    <div id="content-winNuevoUsuarioAdm" class="all">
                        <!--verProceso-->
                    </div>      
                </div>
            </div>
        </div>
    </div>
    
    <div id="lboxReasigClaveUser" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">  
                    <div id="content-lboxReasigClaveUser" class="all">
                        <!--verProceso-->
                    </div>      
                </div>
            </div>
        </div>
    </div>

    <div id="winAdminPerfil" class="window modalInfo">
        <div class="innerWin"> 
            <a href="#Cerrar" id="idCerrarPA" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-winAdminPerfil" class="all">
                        <!--verProceso-->
                    </div>
                </div>    
            </div>
        </div>
    </div>

    <!-- Ejemplo de Ventana Modal -->
    <div id="lboxEeditarOp" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div class="all" id="content-winOpcion">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div id="modalConfirmDeletePA" class="window modalInfo">
        <div class="innerWin"> <a href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="content-modalConfirmDeletePA">
                        <input type="hidden" name="txtidperf" id="txtidperf" value=""/>
                        <h6 class="TilutoLightbox">Mensaje de confirmación</h6>
                        <div id="diagContent" class="infoDialog">
                            ¿ Realmente desea eliminar el perfil ?
                        </div> 
                        <div class="btnMsjModal">
                            <a id="idAceptarOkPA" class="adminAceptBtn left" href="#"></a>
                            <a id="idCancelarEG" class="adminQuitBtnbene closeWM left" href="#"></a>
                        </div>
                    </div>
                    <div id="msjConfirmDelPerfAd"></div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Ventana Cambiar Contraseña : Establecimiento -->
    <?php if(!empty($this->layout()->frmChangePassE)):
        $frmChangePassword = $this->layout()->frmChangePassE; ?>
    <div id="winChangePassE" class="window">
        <div class="innerWin"> <a id="idCloseChangeE" href="#Cerrar" class="sptAll closeWM icoCWM"><span class="hide">Cerrar</span></a>
          <div class="iWindow r5">
              <div class="bLB3 r5 inWindow">
                
                <h6 class="TilutoLightboxES">Cambio de Clave</h6>
                <span class="adminCclaveTi">Para cambiar tu clave, ingresa los siguientes datos:</span>
                  
                <div id="bgmiAdminClave">
                    <form id="cClaveCP" action="<?=SITE_URL.$frmChangePassword->getAction(); ?>" method="post">
                      <fieldset id="mictaCambioClave" class="field textoinput pl10">
                        <div class="block mB0">
                          <label class="adminEslabelN" for="fACtns"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña antigua: </label>
                            <?= $frmChangePassword->oldpswd->setAttribs(array('id' => 'fACtns', 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->oldpswd->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->oldpswd->errMsg : '' ?></span>
                        </div>
                        <div class="block left mB0">
                          <label class="adminEslabelN" for="fClave"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña nueva: </label>
                            <?= $frmChangePassword->pswd->setAttribs(array('id' => 'fClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->pswd->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd->errMsg : '' ?></span>
                        </div>
                        <div class="block mB0">
                          <label class="adminEslabelN" for="fRClave"> 
                            <span class="req" title="Requerido">*</span> 
                            Contraseña nueva:<br/>(confirmación) </label>
                            <?= $frmChangePassword->pswd2->setAttribs(array('id' => 'fRClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                            <? $hasError = $frmChangePassword->pswd2->hasErrors(); ?>
                            <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd2->errMsg : '' ?> </span>
                        </div>
                        <div class="bloque">
                            <input type="submit" id="saveChangesBt" value="" class="btnAll saveChangesBt" tabindex="4"/>
                        </div>
                        <div class="hide messageChangePassE" id="idMessageChangePassE"></div>
                      </fieldset>
                    </form>
                </div>
                
            </div>
          </div>
        </div>
    </div>
    <?php endif; ?>
    
    <div id="mask"></div>
</div>
