<? $activo = 'active'; ?>
<ul id="mainNav" class="grid20 center">
    <?php
    if(!empty($this->layout()->auth['opciones'])){
        $options = $this->layout()->auth['opciones'];
        foreach ($options as $opt):
    ?>
        <li class="<?= ($this->layout()->active == $opt['controlador'] ? $activo : ''); ?> liMianMenu left">
            <a href="<?= $this->url(array('action' => 'index', 'controller' => $opt['controlador'], 'module' => $opt['nombremod']), 'default', true); ?>" class="aMenuMain left"><?php echo $opt['nombreop']; ?></a>
        </li>
    <?php
        endforeach;?>

    <?php }else{
    ?>
    <li class="<?= ($this->layout()->active==App_Controller_Action_Admin::MENU_NAME_INICIO?$activo:''); ?> liMianMenu left">
        <a href="<?= $this->url(array('action'=>'index','controller'=>'home','module'=>'admin'),'default',true); ?>" class="aMenuMain left">Inicio</a>
    </li>
    <li class="<?= ($this->layout()->active==App_Controller_Action_Admin::MENU_NAME_USUARIOS?$activo:''); ?> liMianMenu left">
        <a href="<?= $this->url(array('action'=>'index','controller'=>'usuarios','module'=>'admin'),'default',true); ?>" class="aMenuMain left">Usuarios</a>
    </li>
    <li class="<?= ($this->layout()->active==App_Controller_Action_Admin::MENU_NAME_PERFILES?$activo:''); ?> liMianMenu left">
        <a href="<?= $this->url(array('action'=>'index','controller'=>'perfiles','module'=>'admin'),'default',true); ?>" class="aMenuMain left">Perfiles</a>
    </li>
    <li class="<?= ($this->layout()->active==App_Controller_Action_Admin::MENU_NAME_OPCIONES?$activo:''); ?> liMianMenu left">
        <a href="<?= $this->url(array('action'=>'index','controller'=>'opciones','module'=>'admin'),'default',true); ?>" class="aMenuMain left">Opciones</a>
    </li>
    <?php
    }
    ?>
</ul>

