<script type="text/javascript" src="<?php echo MEDIA_URL.'/js/admin/reasigna_clave.js' ?>"></script>    
<?php $frmChangePassword = $this->formCambioClave; ?>
    <h6 class="TilutoLightboxES">Reasignación de Clave</h6>
    <span class="adminCclaveTi">Para cambiar la clave de un usuario, ingresa los siguientes datos:</span>
    <div id="bgmiAdminClave">
        <form id="cClaveCP" action="<?=$frmChangePassword->getAction(); ?>" method="post">
          <fieldset id="" class="field textoinput pl10">
            <div class="block mB0">
              <label class="adminEslabelN" for="fRol"> 
                <span class="req" title="Requerido">*</span> 
                Perfil: </label>
                <?= $frmChangePassword->cborol->setAttribs(array('id' => 'fRol', 'class' => 'fields inputN ready left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->cborol->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->cborol->errMsg : '' ?></span>
            </div>
            <div class="block mB0">
              <label class="adminEslabelN" for="fSubRol"> 
                <span class="req" title="Requerido">&nbsp;</span> 
                Sub Perfil: </label>
                <?= $frmChangePassword->cbosubrol->setAttribs(array('id' => 'fSubRol', 'class' => 'fields inputN ready left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->cbosubrol->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->cborol->errMsg : '' ?></span>
            </div>
            <div class="block mB0">
              <label class="adminEslabelN" for="fMail">
                <span class="req" title="Requerido">*</span> 
                Email: </label>
                <?= $frmChangePassword->txtemail->setAttribs(array('id' => 'fMail', 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->txtemail->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->txtemail->errMsg : '' ?></span>
            </div>
            <div class="block left mB0">
              <label class="adminEslabelN" for="fClave"> 
                <span class="req" title="Requerido">*</span> 
                Contraseña nueva: </label>
                <?= $frmChangePassword->pswd->setAttribs(array('id' => 'fClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->pswd->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd->errMsg : '' ?></span>
            </div>
            <div class="block mB0">
              <label class="adminEslabelN" for="fRClave"> 
                <span class="req" title="Requerido">*</span> 
                Contraseña nueva:<br/>(confirmación) </label>
                <?= $frmChangePassword->pswd2->setAttribs(array('id' => 'fRClave', 'maxlength' => 32, 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->pswd2->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->pswd2->errMsg : '' ?> </span>
            </div>
            <div class="block mB0">
              <label class="adminEslabelN" for="fACtns"> 
                <span class="req" title="Requerido">*</span> 
                Tu Contraseña: </label>
                <?= $frmChangePassword->oldpswd->setAttribs(array('id' => 'fACtns', 'class' => 'fields inputNmicta inputN left'))->renderViewHelper(); ?>
                <? $hasError = $frmChangePassword->oldpswd->hasErrors(); ?>
                <span class="response cGray2 right <?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $frmChangePassword->oldpswd->errMsg : '' ?></span>
            </div>
            <div class="bloque">
                <input type="submit" id="saveChangesBt" value="" class="btnAll saveChangesBt" tabindex="4"/>
            </div>
            <div class="hide messageChangePassE" id="idMessageChangePassE"></div>
          </fieldset>
        </form>
    </div>