<form id="formBox2" class="grid13">
    <div class="left black"> 
        Estado:
        <?= $this->formFiltroEstablecimiento->estado->setAttribs(array('id' => 'estado', 'class' => 'm15'))->renderViewHelper() ?>
    </div>
<fieldset id="adminformSearch" class="field textoinput right">
    <strong class="">Nombre del Establecimiento:</strong>
    <?= $this->formFiltroEstablecimiento->nombre->setAttribs(array('id' => 'nombre', 'class' => 'cGray  grid4'))->renderViewHelper() ?>
    <input type="button" id="searchbt1" value="" class="btnAll searchbt"/>
</fieldset>
</form>