<form id="formBox2" class="grid13">
    <fieldset id="adminformSearch" class="field textoinput right">
        <label class="labelcnciliaR" for="establecimiento">Módulo:
            <?= $this->filtroModulo->modulo->setAttribs(array('style' => 'width:210px'))->renderViewHelper(); ?>
        </label>
        <input type="button" id="searchbt1" value="" class="btnAll searchbt" />
    </fieldset>
</form>