<div id="MictaMainContentBox" class="gridS20DOS grayborder2 r5">
  <div id="MictaMainBox" class="grid20">
    <?= $this->partial('mi-cuenta/_menu.phtml', array('menu_post_sel' => $this->menu_post_sel)) ?>
    <div id="mictaInnerContent" class="all">
      <?= $this->partial('mi-cuenta/_sidebar_datos_personales.phtml', array('menu_sel_side' => $this->menu_sel_side)) ?>
	    <div id="MictaContentBox" class="right">
	        <?= $this->partial('mi-cuenta/_mis-datos.phtml', array('auth' => $this->auth, 'formSuscriptor' => $this->formSuscriptor)) ?>
	    </div>
    </div>
  </div>
</div>