<?php

/**
 * Description of delta_0029
 *
 * @author DjTabo
 */
class Delta_0029 extends App_Migration_Delta
{
    protected $_autor = 'Paul Carlos Taboada Casas';
    protected $_desc = 'Insertando registros a la tabla parametro - configuracion';

    public function up()
    {
        $ini = new Zend_Config_Ini(APPLICATION_PATH . '/configs/private.ini');
        $private = $ini->toArray();
        
        $sql = 'DELETE FROM parametro;';
        $this->_db->query($sql);
        
        $i = 0; $env = $private['env'];
        /*$param[$i]['nombre'] = 'Twitter consumerKey';
        $param[$i]['descrip'] = '';
        $param[$i]['var'] = 'apis.twitter.consumerKey';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Twitter consumerSecret';
        $param[$i]['descrip'] = '';
        $param[$i]['var'] = 'apis.twitter.consumerSecret';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;*/
        $param[$i]['nombre'] = 'Google appid';
        $param[$i]['descrip'] = 'ID de google para autenticación.';
        $param[$i]['var'] = 'apis.google.appid';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Title';
        $param[$i]['descrip'] = 'Tag Meta title de la pagina. Título de cabecera de la pagina principal';
        $param[$i]['var'] = 'app.title';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'App';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Token User';
        $param[$i]['descrip'] = 'Duración de validez del Token, medida en segundos.';
        $param[$i]['var'] = 'app.tokenUser';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'App';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Max Size File';
        $param[$i]['descrip'] = 'Tamaño maximo permitido para la subida de archivos, medido en Bytes';
        $param[$i]['var'] = 'app.maxSizeFile';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'App';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Session Remember';
        $param[$i]['descrip'] = 'Tiempo de vida del cookie que mantendrá la session abierta (opción "No Cerrar sesión" en ligthbox de Ingreso al Portal); medida en segundos.';
        $param[$i]['var'] = 'app.sessionRemember';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'App';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Life Time ZendAuth';
        $param[$i]['descrip'] = 'Tiempo de vida de la sesión de ZendAuth que permanecerá activa hasta que necesite autentificarse nuevamente; expresada en segundos.';
        $param[$i]['var'] = 'app.lifeTimeZendAuth';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'App';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'app.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'AppId Facebook';
        $param[$i]['descrip'] = 'ID publica de la Api de Facebook para autenticación.';
        $param[$i]['var'] = 'apis.facebook.appid'; //$env.'.apis.facebook.appid';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini'; //'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'AppSecret Facebook';
        $param[$i]['descrip'] = 'ID secreta de la Api de Facebook para autenticación.';
        $param[$i]['var'] = 'apis.facebook.appsecret'; //$env.'.apis.facebook.appsecret';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Recaptcha Public Key';
        $param[$i]['descrip'] = 'Key publica de Recaptcha para validación de formularios Contacto.';
        $param[$i]['var'] = 'recaptcha.publickey';//$env.'.recaptcha.publickey';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Recaptcha Private Key';
        $param[$i]['descrip'] = 'Key privada de Recaptcha para validación de formularios Contacto.';
        $param[$i]['var'] = 'recaptcha.privatekey'; //$env.'.recaptcha.privatekey';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Apis';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'E-mail Contacto';
        $param[$i]['descrip'] = 'Email que recibirá los correos enviados por Contacto del Portal';
        $param[$i]['var'] = 'cuenta.mail.contacto';//$env.'.cuenta.mail.contacto';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Contacto';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'E-mail Suscribete';
        $param[$i]['descrip'] = 'Email que recibirá los correos enviados por Suscripción del Portal';
        $param[$i]['var'] = 'cuenta.mail.suscribete'; //$env.'.cuenta.mail.suscribete';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Contacto';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'E-mail MiCuenta Contacto';
        $param[$i]['descrip'] = 'Email que recibirá los correos enviados por Contacto de Mi Cuenta en el Portal';
        $param[$i]['var'] = 'cuenta.mail.micuenta.contacto'; //$env.'.cuenta.mail.micuenta.contacto';
        $param[$i]['type'] = 'usuario';
        $param[$i]['category'] = 'Contacto';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';//'application.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Catálogo Nro de Beneficios';
        $param[$i]['descrip'] = 'Número de Beneficios mostrados en el catálogo del Portal, por paginado.';
        $param[$i]['var'] = 'beneficios.promos.nropaginas';
        $param[$i]['type'] = 'beneficio';
        $param[$i]['category'] = 'Catalogo';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Sufijo LogoChico de Beneficio';
        $param[$i]['descrip'] = 'Sufijo del nombre de la Imagen Chica del Beneficio.';
        $param[$i]['var'] = 'beneficios.logo.sufix.little';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '0';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '0';
        $i++;
        $param[$i]['nombre'] = 'Sufijo LogoMedio de Beneficio';
        $param[$i]['descrip'] = 'Sufijo del nombre de la Imagen Mediana del Beneficio.';
        $param[$i]['var'] = 'beneficios.logo.sufix.medium';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '0';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '0';
        $i++;
        $param[$i]['nombre'] = 'Sufijo LogoGrande de Beneficio';
        $param[$i]['descrip'] = 'Sufijo del nombre de la Imagen Grande del Beneficio.';
        $param[$i]['var'] = 'beneficios.logo.sufix.big';
        $param[$i]['type'] = 'aplicacion';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '0';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '0';
        $i++;
        $param[$i]['nombre'] = 'Máximo Nro Cupones Quiero la Promo';
        $param[$i]['descrip'] = 'Número de generacion de cupones por defecto, en Quiero la Promo.';
        $param[$i]['var'] = 'beneficios.detalle.nrocupones';
        $param[$i]['type'] = 'beneficio';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro de Beneficios Relacionados';
        $param[$i]['descrip'] = 'Número de Beneficios Relacionados mostrados por pagina, en el Detalle de Beneficio.';
        $param[$i]['var'] = 'beneficios_relacionados.promos.nropaginas';
        $param[$i]['type'] = 'beneficio';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro de Articulos';
        $param[$i]['descrip'] = 'Número de Articulos mostrados por pagina, en Vida Social del Portal.';
        $param[$i]['var'] = 'articulos.nropaginas';
        $param[$i]['type'] = 'vida social';
        $param[$i]['category'] = 'Articulo';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Mis Consumos';
        $param[$i]['descrip'] = 'Número de Consumos mostrados por pagina, en Mi Cuenta - Mis Consumos del Portal.';
        $param[$i]['var'] = 'mis_consumos.nropaginas';
        $param[$i]['type'] = 'mi cuenta';
        $param[$i]['category'] = 'Mis Consumos';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Destacados';
        $param[$i]['descrip'] = 'Número de destacados, mostrados en el Portal Principal.';
        $param[$i]['var'] = 'destacados.nropromos';
        $param[$i]['type'] = 'beneficio';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Consumos por Establecimiento';
        $param[$i]['descrip'] = 'Número de consumos mostrados por página en Reporte de Establecimiento.';
        $param[$i]['var'] = 'establecimiento.consumos.nropaginas';
        $param[$i]['type'] = 'establecimiento';
        $param[$i]['category'] = 'Consumos';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Beneficios por Establecimientos';
        $param[$i]['descrip'] = 'Número de promociones mostradas por página en Promociones Activas de Establecimiento.';
        $param[$i]['var'] = 'establecimiento.beneficios.nropaginas';
        $param[$i]['type'] = 'establecimiento';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Sufijo ImageChica de Galeria';
        $param[$i]['descrip'] = 'Sufijo de la Imagen Chica de la Galeria de Articulos';
        $param[$i]['var'] = 'galeria.sufix.little';
        $param[$i]['type'] = 'vida social';
        $param[$i]['category'] = 'Articulo';
        $param[$i]['editable'] = '0';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '0';
        $i++;
        $param[$i]['nombre'] = 'Nro Usuario - Admin';
        $param[$i]['descrip'] = 'Número de usuarios mostrados por página en Admin - Mantenimiento de Usuarios';
        $param[$i]['var'] = 'admin.usuarios.nropaginas';
        $param[$i]['type'] = 'admin';
        $param[$i]['category'] = 'Usuario';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Articulos - Gestor';
        $param[$i]['descrip'] = 'Número de articulos mostrados por página en Gestor - Mantenimiento de Articulos';
        $param[$i]['var'] = 'gestor.articulos.nropaginas';
        $param[$i]['type'] = 'gestor';
        $param[$i]['category'] = 'Artículo';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Encuestas - Gestor';
        $param[$i]['descrip'] = 'Número de encuestas mostradas por página en Gestor - Mantenimiento de Encuestas';
        $param[$i]['var'] = 'gestor.encuestas.nropaginas';
        $param[$i]['type'] = 'gestor';
        $param[$i]['category'] = 'Encuesta';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        $param[$i]['nombre'] = 'Nro Promos - Gestor';
        $param[$i]['descrip'] = 'Número de beneficios mostrados por página en Gestor - Mantenimiento de Beneficios';
        $param[$i]['var'] = 'gestor.promos.nropaginas';
        $param[$i]['type'] = 'gestor';
        $param[$i]['category'] = 'Beneficio';
        $param[$i]['editable'] = '1';
        $param[$i]['archivo'] = 'cs.ini';
        $param[$i]['update'] = '1';
        $i++;
        
        
        $sql = "INSERT INTO `parametro` (`actualizado_por`, `nombre`, `descripcion`, `variable`, 
            `valor`, `tipo`, `categoria`, `es_editable`, `archivo`, `actualizar`, `fecha_registro`, 
            `fecha_actualizacion`) VALUES ";
        foreach ($param as $p):
            $name = $p['nombre'];
            $descrip = $p['descrip'];
            $var = $p['var'];
            $value = '';
            $type = $p['type'];
            $category = $p['category'];
            $editable = $p['editable'];
            $archivo = $p['archivo'];
            $update = $p['update'];
            $fecreg = date('Y-m-d h:i:s');
            
            $valor = explode('.', $p['var']);
            $execute = '';
            foreach ($valor as $indice):
                $execute.="['".$indice."']";
            endforeach;
            $pathFile = APPLICATION_PATH . '/configs/'.$p['archivo'];
            $x = new Zend_Config_Ini($pathFile);
            $arreglo = $x->toArray();
            eval('$value = $arreglo'.$execute.';');
            
        $sql .= "('1', '".$name."', '".$descrip."', '".$var."', '".$value."', '".$type."', '".$category."', 
            '".$editable."', '".$archivo."', '".$update."', '".$fecreg."', '".$fecreg."'),";
            
        endforeach;
        $sql = substr($sql, 0, -1);
        //echo $sql; exit;
        $this->_db->query($sql);
        return true;
    }

}
