<div id="contAnunciante">
    <h6 class="Titulo980 bold">ANUNCIANTES ASOCIADOS</h6>
    <div id="adminActivtyBoxR" class="right">
        <?=$this->partial('anunciante/_filtro_anunciante.phtml',
                          array('formFiltroAnunciante' => $this->formFiltroAnunciante)) ?>
    </div>
    <div id="adminActivty2" class="">
        <a href="<?= $this->url(array(
                'action' => 'nuevo-anunciante', 
                'controller' => 'anunciante', 
                'module' => 'gestor'), 
            'default', true) ?>" class="adminAdBtn left">
        </a>
    </div>
    <div id="adminEstaContentBox" class="grid17 right">
    </div>
</div>
<div id="ajax-loading" class="loading hide" style="width: 100%;"></div>
<div id="csrf_base" class="hide"><?=$this->csrf?></div>