<h6 class="TilutoLightbox">Baja de Beneficio</h6>
<div class="block pl10" id="vcont"> 
    <span class="Trebuchet14 gray"><?php echo $this->msj; ?></span>
    <input type="hidden" name="txtidBenef" id="txtidBenef" value="<?php echo $this->id; ?>" />
</div>
<div id="adminSaveCancEB" class="marginCero">
    <a id="aceptBajaBenefBtn" class="adminAceptBtn left" href="#"></a>
    <a id="aCloseBajaB" class="adminQuitBtnbene left closeWM" href="#"></a>
</div>